# -*- coding: utf-8 -*-
"""Data Cleaning .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17esTpYEUe-f2am3PJt2keqkbecjtyK7w
"""

# Importing necessary libraries

import numpy as np
import pandas as pd
import seaborn as sns
import os
import matplotlib.pyplot as plt

"""## Loading the dataset

Data Set Source:

https://www.kaggle.com/datasets/gianinamariapetrascu/gender-inequality-index/data
"""

# Reading as df with pandas

gender_df = pd.read_csv('/content/Gender_Inequality_Index.csv')

"""## Data understanding"""

gender_df.head(5)

gender_df.shape

gender_df.info()



"""## Data Cleaning

Null Values
"""

# Showing the number of null values

gender_df.isnull().sum()

"""% of Null value in dataset"""

(gender_df.isnull().sum()/gender_df.shape[0])*100

sns.heatmap(gender_df.isnull(), yticklabels = False)

"""Dropping null values"""

gender_df.dropna(inplace=True)

gender_df.isnull().sum()

"""checking for duplicated values


"""

gender_df.duplicated().sum()

"""Adding country codes column"""

!pip install pycountry

import pycountry

input_countries = gender_df['Country']

countries = {}
for country in pycountry.countries:
    countries[country.name] = country.alpha_3

codes = [countries.get(country) for country in input_countries]

print(codes)

gender_df['ISO-Code']=codes

gender_df.head(5)

# Rearranging the columns

# Move ISO-Code column to the first position
iso_code_col = gender_df.pop('ISO-Code')
gender_df.insert(0, 'ISO-Code', iso_code_col)

# Rearranged columns

gender_df.head(2)

"""# Data Export"""

# Exporting processed data for further analysis in flourish

gender_df.to_csv("Cleaned gender Data.csv",index=False)

